name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Publish ora2mqtt Windows
      run: dotnet publish -c release -r win-x64 --sc ora2mqtt/ora2mqtt.csproj
    - name: Publish ora2mqtt Linux
      run: dotnet publish -c release -r linux-x64 --sc ora2mqtt/ora2mqtt.csproj
    - name: Publish ora2mqtt Linux ARM
      run: dotnet publish -c release -r linux-arm --sc ora2mqtt/ora2mqtt.csproj
    - name: Publish ora2mqtt Linux ARM64
      run: dotnet publish -c release -r linux-arm64 --sc ora2mqtt/ora2mqtt.csproj
    - uses: actions/upload-artifact@v4
      with:
        name: ora2mqtt-win-x64
        path: ora2mqtt/bin/release/net8.0/win-x64/publish
    - uses: actions/upload-artifact@v4
      with:
        name: ora2mqtt-linux-x64
        path: ora2mqtt/bin/release/net8.0/linux-x64/publish
    - uses: actions/upload-artifact@v4
      with:
        name: ora2mqtt-linux-arm
        path: ora2mqtt/bin/release/net8.0/linux-arm/publish
    - uses: actions/upload-artifact@v4
      with:
        name: ora2mqtt-linux-arm64
        path: ora2mqtt/bin/release/net8.0/linux-arm64/publish